services:
  liji-init:
    image: busybox:latest
    volumes:
      - ./data:/app/data
    command: sh -c "mkdir -p /app/data && chown -R 1000:1000 /app/data"
    user: "0:0"

  liji-app:
    image: zsw01442/liji:latest
    container_name: liji
    depends_on:
      - liji-init
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATA_DIR=/app/data
    user: "1000:1000"
    restart: unless-stopped

name: liji
